name: bpm_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - scipy
  - librosa
  - tqdm
  - ffmpeg
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.8 # 如果你没有GPU，请删掉此行并加上 cpuonly
  - pip
  - pip:
      - soundfile # pip 版本 = pysoundfile
      - transformers==4.38
      - accelerate
      - huggingface-hub
